### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by 3052** [pandvan/rakuten-m3u-generator#2]
~~~
PS D:\Desktop\rakuten-m3u-generator-master> python.exe .\main.py
Traceback (most recent call last):
  File "D:\Desktop\rakuten-m3u-generator-master\main.py", line 48, in <module>
    sys.exit(main())
  File "D:\Desktop\rakuten-m3u-generator-master\main.py", line 43, in main
    m3u_list = generate_list(channels)
  File "D:\Desktop\rakuten-m3u-generator-master\main.py", line 22, in generate_list
    ch_streams = rakuten.map_channels_streams(channels)
  File "D:\Desktop\rakuten-m3u-generator-master\rakuten.py", line 162, in map_channels_streams
    .get("url", "# no_url")
AttributeError: 'NoneType' object has no attribute 'get'
~~~

**Comment by pandvan** [comment]
Thanks for reporting this.
Could you please retry? It may be a temporary issue of Rakuten APIs. I haven't investigated this yet, but CI pipeline last run worked properly.

**Comment by purplescorpion1** [comment]
I have the issue too 

I put in a graceful error handling into the code as shown below

The issue is stream_infos is empty


```
# system imports
# import pprint
from collections import namedtuple
from typing import List

# 3rd parties imports
import requests


# Channel definition
CHANNEL_FIELDS = [
    "id",
    "numerical_id",
    "title",
    "type",
    "channel_number",
    "category",
    "language_ids",
]

Channel = namedtuple("Channel", CHANNEL_FIELDS)


class Api:
    api_scheme = "https"
    api_domain = "gizmo.rakuten.tv"
    api_base_path = "/v3"
    api_base_url = "{}://{}{}".format(
        api_scheme,
        api_domain,
        api_base_path
    )

    origin = "https://rakuten.tv"
    referer = "https://rakuten.tv/"
    user_agent = "Mozilla/5.0 (X11; Linux x86_64; rv:98.0) Gecko/20100101 Firefox/98.0"

    language = "it"


    @classmethod
    def get_live_channels(cls):
        path = "/live_channels"
        headers = {
            "Origin": cls.origin,
            "Referer": cls.referer,
            "User_Agent": cls.user_agent,
        }
        query = {
            "classification_id": 36,
            "device_identifier": "web",
            "locale": cls.language,
            "market_code": cls.language,
            "page": 1,
            "per_page": 100,
        }

        response = requests.get(
            cls.api_base_url + path,
            headers=headers,
            params=query,
        )

        return response.json()


    @classmethod
    def get_live_channel_categories(cls):
        path = "/live_channel_categories"
        headers = {
            "Origin": cls.origin,
            "Referer": cls.referer,
            "User_Agent": cls.user_agent,
        }
        query = {
            "classification_id": 36,
            "device_identifier": "web",
            "locale": cls.language,
            "market_code": cls.language
        }

        response = requests.get(
            cls.api_base_url + path,
            headers=headers,
            params=query,
        )

        return response.json()

    
    @classmethod
    def get_live_streaming(cls, channel: Channel, session: requests.Session = None):
        path = "/avod/streamings"
        headers = {
            "Origin": cls.origin,
            "Referer": cls.referer,
            "User_Agent": cls.user_agent,
        }
        query = {
            "classification_id": 36,
            "device_identifier": "web",
            "device_stream_audio_quality": "2.0",
            "device_stream_hdr_type": "NONE",
            "device_stream_video_quality": "FHD",
            "disable_dash_legacy_packages": False,
            "locale": cls.language,
            "market_code": cls.language
        }

        data = {
            "audio_language": channel.language_ids[0],
            "audio_quality": "2.0",
            "classification_id": "36",
            "content_id": channel.id,
            "content_type": "live_channels",
            "device_serial": "not implemented",
            "player": "web:HLS-NONE:NONE",
            "strict_video_quality": False,
            "subtitle_language": "MIS",
            "video_type": "stream"
        }

        if session:
            caller = session
        else:
            caller = requests
        
        response = caller.post(
            cls.api_base_url + path,
            headers=headers,
            params=query,
            json=data,
        )

        return response.json()


# methods
def map_channels_categories(api_response):
    categories = api_response.get("data", [])
    
    channels_categories_map = {}
    for category in categories:
        name = category.get("name", "no_category")
        channels = category.get("live_channels", [])

        for channel in channels:
            channels_categories_map[channel] = name
    
    return channels_categories_map


def map_channels_streams(channels: List[Channel]):
    session = requests.Session()

    ch_stream_map = {}

    for channel in channels:
        response = Api.get_live_streaming(channel, session)
        stream_infos = response.get("data", {}).get("stream_infos", [])

        # Check if stream_infos is not empty and get the URL, else set it to "# no_url"
        if stream_infos:
            stream_url = stream_infos[0].get("url", "# no_url")
        else:
            stream_url = "# no_url"

        ch_stream_map[channel.id] = stream_url
    
    return ch_stream_map


def get_channels():
    live_channels_raw = Api.get_live_channels()
    categories_raw = Api.get_live_channel_categories()

    # pprint.pprint(live_channels)
    # print("\n\n\n\n")
    # pprint.pprint(categories)
    
    # make channels/category lookup map
    cc_map = map_channels_categories(categories_raw)
    
    # list of all live channels
    ch_list: List(Channels) = []

    channels = live_channels_raw.get("data", [])
    for channel in channels:
        
        ch_id = channel.get("id", "no_id")

        ch_languages = channel.get("labels", {}).get("languages", [])
        langs = []

        for lang in ch_languages:
            langs.append(lang.get("id"))
        
        ch = Channel(
            id = ch_id,
            numerical_id = int(channel.get("numerical_id", -1)),
            title = channel.get("title", "no_title"),
            type = channel.get("type", "no_type"),
            channel_number = int(channel.get("channel_number", -1)),
            category = cc_map.get(ch_id, "no_category"),
            language_ids = langs,
        )

        ch_list.append(ch)

    # pprint.pprint(ch_list)
    return ch_list
```

So I can see all the streams it is trying to scrape but each of them reports no_url

Will this only work on Italian IPs or can this be run from anywhere?

**Comment by 3052** [comment]
@purplescorpion1 please dont spam the issue with your massive code block

**Comment by pandvan** [comment]
> Will this only work on Italian IPs or can this be run from anywhere?

Rakuten APIs are geo blocked for what I remember.
In fact I need to use a proxy to make it work on GitHub Actions managed workers.

**Comment by pandvan** [comment]
> closing this because I wrote my own tool

I would be great if you decide to make it open source...

**Comment by pandvan** [comment]
> I have the issue too

Today CI runs starts to fail
Maybe something has changed on their side... incredible that I worked for so many years without any intervention

**Comment by 3052** [comment]
https://github.com/3052/media/tree/main/internal/rakuten

**Comment by Malmis** [comment]
This can be solved by changing the language and classification_id

```
  language = "se"
  classification_id = 282
```
also change all "classification_id": 36, to:
` "classification_id": cls.classification_id,`

More languages can be found if you look in the debug tool in browser searching for classification to get your classification id, for your country
![image](https://github.com/user-attachments/assets/cdc5f990-dd94-4a0b-9ae4-f81481fb231f)

Some more examples:

    #language = "de"
    #classification_id = 307

    #language = "it"
    #classification_id = 36

    #language = "uk"
    #classification_id = 18

    #language = "pl"
    #classification_id = 277

    #language = "fr"
    #classification_id = 23

    #language = "nl"
    #classification_id = 69

    #language = "no"
    #classification_id = 286

    #language = "ro"
    #classification_id = 268

    #language = "ch"
    #classification_id = 319

**Comment by pandvan** [comment]
The project is now able to support multiple language.
Just have a look at the README on how to setup your preferred language.

Please remind that Rakuten's APIs are geoblocked so you can get list only for the country where you are (or need to use other means...)
